### PR TITLE
Sudw∩m types

### PR DESCRIPTION
**Pull request by Pjt727**

### CODE REVIEW

**Comment by andrewdoherty1** [comment]
I like having Entity state, I think it can be used in sync with a Room/Cave data type. My group just has a list of Entity's I think it would be good to add this to ours!

**Comment by willponzer** [comment]
I like your dodecahedron creation, I also like the idea to add the current and previous position to the player, rather than just having the current position.

**Review by nicholas-longo — APPROVED** [review]

**Review by thecryptobeserker — DISMISSED** [review]

**Review by JoshuaChenoweth — APPROVED** [review]

**Review by HarrisLich — DISMISSED** [review]

**Review by ConnorFleischman — APPROVED** [review]
I prefer this implementation of the map. I also feel it effectively represents the information required for the player, the game, and the entities in the game. 

I feel this is the best avenue for progressing the project.

**Comment by Tientuine** [comment]
Merging after class consensus.

**Comment by Tientuine** [comment]
Merging after class consensus.

**Comment by ZachHappel** [comment]
I like the inclusion of Last Position. If I recall correctly, I spoke about this in class on Monday and I am glad to see others were thinking along the same lines.

**Pull request merged**
